![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [28]:
import sys
import numpy as np

## Basic Numpy Arrays

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [12]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [13]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [15]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [16]:
a

array([1, 2, 3, 4])

In [17]:
a.dtype

dtype('int64')

In [18]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
b.dtype

dtype('float64')

In [22]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [21]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [23]:
c = np.array(['a', 'b', 'c'])

In [24]:
c.dtype

dtype('<U1')

In [25]:
d = np.array([{'a': 1}, sys])

In [26]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [28]:
A.shape

(2, 3)

In [30]:
A.ndim

2

In [29]:
A.size

6

In [31]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [32]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [33]:
B.shape

(2, 2, 3)

In [34]:
B.ndim

3

In [35]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [36]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [37]:
C.dtype

NameError: name 'C' is not defined

In [38]:
C.shape

NameError: name 'C' is not defined

In [39]:
C.size

NameError: name 'C' is not defined

In [40]:
type(C[0])

NameError: name 'C' is not defined

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [49]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [41]:
A.shape

(2, 3)

In [42]:
A.ndim

2

In [43]:
A[1]

array([4, 5, 6])

In [44]:
A[1][0]

np.int64(4)

In [ ]:
# A[d1, d2, d3, d4]

In [45]:
A[1, 0]

np.int64(4)

In [50]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [53]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
A[1] = np.array([10, 10, 10])

In [55]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [56]:
A[2] = 99

In [57]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [58]:
a = np.array([1, 2, 3, 4])

In [59]:
a.sum()

np.int64(10)

In [60]:
a.mean()

np.float64(2.5)

In [61]:
a.std()

np.float64(1.118033988749895)

In [62]:
a.var()

np.float64(1.25)

In [63]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [64]:
A.sum()

np.int64(45)

In [65]:
A.mean()

np.float64(5.0)

In [66]:
A.std()

np.float64(2.581988897471611)

In [67]:
A.sum(axis=0)

array([12, 15, 18])

In [69]:
A.sum(axis=1)

array([ 6, 15, 24])

In [70]:
A.mean(axis=0)

array([4., 5., 6.])

In [71]:
A.mean(axis=1)

array([2., 5., 8.])

In [72]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [73]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [3]:
import numpy as np


In [4]:
a = np.arange(4)

In [5]:
a

array([0, 1, 2, 3])

In [6]:
a + 10

array([10, 11, 12, 13])

In [7]:
a * 10

array([ 0, 10, 20, 30])

In [8]:
a

array([0, 1, 2, 3])

In [9]:
a += 100

In [10]:
a

array([100, 101, 102, 103])

In [11]:
l = [0, 1, 2, 3]

In [12]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [13]:
a = np.arange(4)

In [14]:
a

array([0, 1, 2, 3])

In [15]:
b = np.array([10, 10, 10, 10])

In [16]:
b

array([10, 10, 10, 10])

In [17]:
a + b

array([10, 11, 12, 13])

In [18]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a[0], a[-1]

(0, 3)

In [ ]:
a[[0, -1]]

array([0, 3])

In [ ]:
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[~(a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [19]:
A = np.random.randint(100, size=(3, 3))

In [22]:
A

array([[ 7, 27, 29],
       [42, 15, 49],
       [38, 64, 94]])

In [23]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([ 7, 29, 15, 38, 94])

In [24]:
A > 30

array([[False, False, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [25]:
A[A > 30]

array([42, 49, 38, 64, 94])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [6]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [7]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [8]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [9]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [10]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [11]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [29]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [30]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [31]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [32]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [33]:
np.dtype(float).itemsize

8

### Lists are even larger

In [34]:
# A one-element list
sys.getsizeof([1])

64

In [35]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [1]:
l = list(range(100000000))

In [3]:
import sys
import numpy as np
a = np.arange(100000000)

In [5]:
%time np.sum(a ** 2)

CPU times: user 213 ms, sys: 170 ms, total: 383 ms
Wall time: 382 ms


np.int64(662921401752298880)

In [4]:
%time sum([x ** 2 for x in l])

CPU times: user 10.2 s, sys: 2.29 s, total: 12.4 s
Wall time: 12.5 s


333333328333333350000000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random`

In [13]:
np.random.random(size=2)

array([0.14880505, 0.99698694])

In [14]:
np.random.normal(size=2)

array([1.03813635, 0.19739999])

In [15]:
np.random.rand(2, 4)

array([[0.91286128, 0.80620264, 0.46146913, 0.94051425],
       [0.00229073, 0.18982827, 0.14552573, 0.1588841 ]])

---
### `arange`

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [18]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [19]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [21]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [23]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros((3, 3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [37]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)